### ISSUE TITLE
Adding non-ABS feature types

### ISSUE THREAD

**Issue by ashleysommer** [CSIRO-enviro-informatics/asgs-dataset#18]
Issues:

1) Theres two different disagreeing diagrams for depicting non-abs features:
  i) https://www.abs.gov.au/websitedbs/D3310114.nsf/4a256353001af3ed4b2562bb00121564/c453c497aadde71cca2576d300026a38/Body/2.1E7E!OpenElement&FieldElemFormat=jpg
  ii) https://www.abs.gov.au/websitedbs/censushome.nsf/4a256353001af3ed4b2562bb00121564/9af8a161fdf844dcca257a4b000a6124/Body/0.1BD2!OpenElement&FieldElemFormat=gif

2) Features LGAs and SEDs both change regularly, and the data is updated accordinly in "volumes" and "editions' of ASGS. https://www.abs.gov.au/ausstats/abs@.nsf/mf/1270.0.55.003

**Comment by dr-shorthair** [comment]
I started here https://www.abs.gov.au/websitedbs/D3310114.nsf/home/Australian+Statistical+Geography+Standard+(ASGS) and followed the link to https://www.abs.gov.au/ausstats/abs@.nsf/mf/1270.0.55.003

Destination zones are _not_ included, but I found the description here: https://www.abs.gov.au/ausstats/abs@.nsf/mf/8000.0

**Comment by dr-shorthair** [comment]
I found the 2016 version of Volume 3 here: https://www.abs.gov.au/ausstats/abs@.nsf/Lookup/by%20Subject/1270.0.55.003~July%202016~Main%20Features~Non%20ABS%20Structures~3 
If you look at the descriptions of the various classes, you'll see that they changed from SA1 to MBs between 2011 and 2016.

But the 2019 version only describes LGAs and SEDs.

**Comment by jyucsiro** [comment]
@ashleysommer from discussions today - we were advised to drop POA as they are not very reliable. so omit that from the list

**Comment by ashleysommer** [comment]
Ok. Dropping POA.
So for These non-ABS features, I'm doing LGA, SSC, NRMR.
Do we want SED or CED or both?
Any need for Tourism Region or ADD?

**Comment by jyucsiro** [comment]
On the list I thought we had LGA, SSC, NRMR and CED. Let's go with this first. They are approximations so would be good to evaluate how useful they are...

**Comment by jyucsiro** [comment]
These have now been added in the new cache.

**Comment by dr-shorthair** [comment]
POAs from ABS are not very reliable. Australia Post changes them regularly and without notice - they are primarily to assist mail sorting and delivery, so are related to the configuration of post offices and suburbs, which change on an arbitrary schedule. 

Having said that, however, a lot of commercial and survey practices use Post Codes as if they were a stable statistical unit, which is why ABS includes them at all. So I'm not sure they really should be removed - it will reduce the credibility of Loc-I if they are not present.
